apiVersion: v1
kind: Pod
metadata:
  name: store-backend
  namespace: app-namespace
  labels:
    app: backend
spec:
  containers:
  - name: backend
    image: busybox
    args:
    - sh
    - -c
    - >
      while true; do
        nc -z db 5432 || exit 1;
        sleep 5;
      done;
