apiVersion: v1
kind: Pod
metadata:
  name: db
  namespace: app-namespace
  labels:
    app: database
spec:
  containers:
  - name: postgres
    image: postgres:13
    env:
    - name: POSTGRES_USER
      value: user
    - name: POSTGRES_PASSWORD
      value: password
    - name: POSTGRES_DB
      value: storedb
    ports:
    - containerPort: 5432
      name: postgres
